# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLy9RJgfvUbusKOZbQXtsD18opltm0rz
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# Sample Housing Dataset
data = {
    'area': [1000, 1500, 1800, 2400, 3000, 3500, 4000, 4500, 5000, 5500],
    'bedrooms': [2, 3, 3, 4, 4, 4, 5, 5, 5, 6],
    'bathrooms': [1, 2, 2, 3, 3, 3, 4, 4, 4, 5],
    'price': [2500000, 3800000, 4200000, 5800000, 7000000, 7200000, 8500000, 9200000, 9800000, 11000000]
}

df = pd.DataFrame(data)

# Splitting X and y
X = df.drop('price', axis=1)
y = df['price']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Output
y_pred = model.predict(X_test)
print("Model Successfully Trained!")
print("R2 Score:", round(r2_score(y_test, y_pred), 2))
print("Mean Absolute Error:", round(mean_absolute_error(y_test, y_pred), 2))